### ISSUE TITLE
Rename *task* to *job*

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zbctl#30]
Following the discussion in https://github.com/zeebe-io/zeebe/issues/694

**Comment by menski** [comment]
I don't think this issue is finished: https://github.com/zeebe-io/zbctl/search?q=task&unscoped_q=task

**Comment by jsam** [comment]
this ticket is in wrong repository ... remaining renamings needs to be done in zbc-go

**Comment by menski** [comment]
There is still this left.

```
bash-4.3# zbctl subscribe job                                                                                                                                                                           
Subscribe to topic or task                                                                                                                                                                              

Usage:
  zbctl subscribe [command]

Available Commands:
  task        Open task subscription and attach a handler script to process every task.
```

 We should probably rename this to job worker somehow. Maybe `zbctl worker` is enough?

**Comment by jsam** [comment]
Which commit are you looking? This is not master. Also, please refer to the ticket which actually is considering this on zbc-go.

**Comment by menski** [comment]
This is from inside the 0.10.0 docker container so I guess it is from the zbctl packaged in the release :thinking:

**Comment by menski** [comment]
It seems that the release was build between two renaming commits where the last one contained the job subscriptions changes. The Jenkins pipeline was triggered around 12:38 and this commit https://github.com/zeebe-io/zbctl/commit/38e1613e4c4ce8f7977ff14f9e9ee67685ef0809 was pushed to master around 12:40 at which point zbctl was build already as we can see in the https://github.com/zeebe-io/zbctl/tree/0.10.0 tag which does not contain the later commit.
