### ISSUE TITLE
Improve output of create workflow

### ISSUE THREAD

**Issue by menski** [zeebe-io/zbctl#36]
Currently the `create workflow` command returns `null` on success. I would prefer to get the process id and workflow key of the deployed processes. 

```
$ zbctl create workflow order-process.bpmn                                                         
null 
```

**Comment by jsam** [comment]
This should be fixed on zbc-go side. I would close this ticket here as zbctl code is fine and the actual issue is there imho.

I opened and described this issue there: https://github.com/zeebe-io/zbc-go/issues/180

Close this ticket if you agree.

**Comment by menski** [comment]
I wasn't sure where the fix has to be and I experience the issue with zbctl that's why I created the issue here. But you are right the fix is in zbc-go. I created a pull request.
